openapi: 3.1.0
info:
  title: MedlAI Endpoints
  description: Endpoints documentation for MedlAI backend
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /admin/doctors/get:
    get:
      summary: "GET admin/doctors/get"
      operationId: "getAllDoctors"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AdminDoctorDTO"
  /admin/doctors/create:
    post:
      summary: "POST admin/doctors/create"
      operationId: "createDoctor"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Doctor"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Doctor"
  /admin/doctors/{id}:
    delete:
      summary: "DELETE admin/doctors/{id}"
      operationId: "deleteDoctor"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
    get:
      summary: "GET admin/doctors/{id}"
      operationId: "getDoctorById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AdminDoctorDTO"
    put:
      summary: "PUT admin/doctors/{id}"
      operationId: "updateDoctor"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Doctor"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Doctor"
  /admin/absences/get:
    get:
      summary: "GET admin/absences/get"
      operationId: "getAllAbsences"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AbsenceDTO"
  /admin/absences/{id}:
    get:
      summary: "GET admin/absences/{id}"
      operationId: "getAbsenceById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AbsenceDTO"
    put:
      summary: "PUT admin/absences/{id}"
      operationId: "updateAbsence"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Absence"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Absence"
    delete:
      summary: "DELETE admin/absences/{id}"
      operationId: "deleteAbsence"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
  /admin/absences:
    post:
      summary: "POST admin/absences"
      operationId: "createAbsence"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AbsenceDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AbsenceDTO"
  /admin/appointment/get:
    get:
      summary: "GET admin/appointment/get"
      operationId: "getAllAppointments"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AdminAppointmentDTO"
  /admin/appointment/{id}:
    get:
      summary: "GET admin/appointment/{id}"
      operationId: "getAppointmentById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Appointment"
    put:
      summary: "PUT admin/appointment/{id}"
      operationId: "updateAppointment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Appointment"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Appointment"
  /admin/appointment:
    post:
      summary: "POST admin/appointment"
      operationId: "createAppointment"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Appointment"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Appointment"
  /admin/appointments/{id}:
    delete:
      summary: "DELETE admin/appointments/{id}"
      operationId: "deleteAppointment"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
  /admin/schedules/get:
    get:
      summary: "GET admin/schedules/get"
      operationId: "getAllSchedules"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ScheduleDTO"
  /admin/schedules/{id}:
    put:
      summary: "PUT admin/schedules/{id}"
      operationId: "updateSchedule"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Schedule"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Schedule"
    get:
      summary: "GET admin/schedules/{id}"
      operationId: "getScheduleById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ScheduleDTO"
    delete:
      summary: "DELETE admin/schedules/{id}"
      operationId: "deleteSchedule"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
  /admin/schedules:
    post:
      summary: "POST admin/schedules"
      operationId: "createSchedule"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduleDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ScheduleDTO"
    /api/appointment/add:
      post:
        summary: "POST api/appointment/add"
        operationId: "add"
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppointmentBookedDTO"
          required: true
        responses:
          "200":
            description: "OK"
            content:
              '*/*':
                schema:
                  $ref: "#/components/schemas/AppointmentBookedDTO"
    /api/appointment/get:
      get:
        summary: "GET api/appointment/get"
        operationId: "getAvailableAppointments"
        parameters:
          - name: "doctorID"
            in: "query"
            required: true
            schema:
              type: "integer"
              format: "int32"
          - name: "date"
            in: "query"
            required: true
            schema:
              type: "string"
        responses:
          "200":
            description: "OK"
            content:
              '*/*':
                schema:
                  type: "array"
                  items:
                    $ref: "#/components/schemas/AppointmentDTO"
  /api/appointment/getconfirmation:
    get:
      summary: "GET api/appointment/getconfirmation"
      operationId: "getConfirmAppointment"
      parameters:
        - name: "token"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AppointmentConfirmationDTO"
  /api/appointment/confirm:
    post:
      summary: "POST api/appointment/confirm"
      operationId: "confirmAppointment"
      requestBody:
        content:
          application/json:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /api/appointment/cancel:
    post:
      summary: "POST api/appointment/cancel"
      operationId: "cancelAppointment"
      requestBody:
        content:
          application/json:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /api/doctor/get:
    get:
      summary: "GET api/doctor/get"
      operationId: "getDoctors"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DoctorDTO"


components:
  schemas:
    AdminDoctorDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        first_name:
          type: "string"
        last_name:
          type: "string"
        email:
          type: "string"
        phone:
          type: "string"
        specialization:
          type: "string"
          enum:
            - "GENERAL"
            - "CARDIOLOGIST"
            - "NEUROLOGIST"
            - "DERMATOLOGIST"
            - "ONCOLOGIST"
            - "PEDIATRICIAN"
            - "PSYCHIATRIST"
            - "OPHTHALMOLOGIST"
            - "GASTROENTEROLOGIST"
            - "ENDOCRINOLOGIST"
    Appointment:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        start_date:
          type: "string"
          format: "date-time"
        patient_first_name:
          type: "string"
        patient_last_name:
          type: "string"
        patient_email:
          type: "string"
        patient_phone:
          type: "string"
        patient_address:
          type: "string"
        patient_pesel:
          type: "string"
        doctor:
          $ref: "#/components/schemas/Doctor"
        status:
          type: "string"
          enum:
            - "SCHEDULED"
            - "COMPLETED"
            - "CANCELLED"
            - "TO_BE_CONFIRMED"
    Schedule:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        day_of_week:
          type: "string"
          enum:
            - "MONDAY"
            - "TUESDAY"
            - "WEDNESDAY"
            - "THURSDAY"
            - "FRIDAY"
            - "SATURDAY"
            - "SUNDAY"
        start_time:
          type: "string"
          format: "partial-time"
        end_time:
          type: "string"
          format: "partial-time"
        valid_to:
          type: "string"
          format: "date"
        doctor:
          $ref: "#/components/schemas/Doctor"
    Absence:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        start_date:
          type: "string"
          format: "date"
        end_date:
          type: "string"
          format: "date"
        absence_reason:
          type: "string"
          enum:
            - "VACATION"
            - "L4"
            - "CHILDCARE"
            - "OTHER"
        doctor:
          $ref: "#/components/schemas/Doctor"
    Doctor:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        first_name:
          type: "string"
        last_name:
          type: "string"
        email:
          type: "string"
        phone:
          type: "string"
        specialization:
          type: "string"
          enum:
            - "GENERAL"
            - "CARDIOLOGIST"
            - "NEUROLOGIST"
            - "DERMATOLOGIST"
            - "ONCOLOGIST"
            - "PEDIATRICIAN"
            - "PSYCHIATRIST"
            - "OPHTHALMOLOGIST"
            - "GASTROENTEROLOGIST"
            - "ENDOCRINOLOGIST"
        appointments:
          type: "array"
          items:
            $ref: "#/components/schemas/Appointment"
        schedule:
          type: "array"
          items:
            $ref: "#/components/schemas/Schedule"
        absence:
          type: "array"
          items:
            $ref: "#/components/schemas/Absence"
    Void:
      type: "object"
      properties: { }
    AbsenceDTO:
      type: "object"
      properties:
        doctor_id:
          type: "integer"
          format: "int32"
        id:
          type: "integer"
          format: "int32"
        start_date:
          type: "string"
          format: "date"
        end_date:
          type: "string"
          format: "date"
        absence_reason:
          type: "string"
          enum:
            - "VACATION"
            - "L4"
            - "CHILDCARE"
            - "OTHER"
    AdminAppointmentDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        start_date:
          type: "string"
          format: "date-time"
        patient_first_name:
          type: "string"
        patient_last_name:
          type: "string"
        patient_email:
          type: "string"
        patient_phone:
          type: "string"
        patient_address:
          type: "string"
        patient_pesel:
          type: "string"
        doctor_id:
          type: "integer"
          format: "int32"
        status:
          type: "string"
          enum:
            - "SCHEDULED"
            - "COMPLETED"
            - "CANCELLED"
            - "TO_BE_CONFIRMED"
    ScheduleDTO:
      type: "object"
      properties:
        doctor_id:
          type: "integer"
          format: "int32"
        id:
          type: "integer"
          format: "int32"
        day_of_week:
          type: "string"
          enum:
            - "MONDAY"
            - "TUESDAY"
            - "WEDNESDAY"
            - "THURSDAY"
            - "FRIDAY"
            - "SATURDAY"
            - "SUNDAY"
        start_time:
          type: "string"
          format: "partial-time"
        end_time:
          type: "string"
          format: "partial-time"
        valid_to:
          type: "string"
          format: "date"
    AppointmentBookedDTO:
      type: "object"
      properties:
        doctor_id:
          type: "integer"
          format: "int32"
        start_date:
          type: "string"
          format: "date-time"
        patient_first_name:
          type: "string"
        patient_last_name:
          type: "string"
        patient_email:
          type: "string"
        patient_phone:
          type: "string"
        patient_pesel:
          type: "string"
        patient_address:
          type: "string"
        status:
          type: "string"
          enum:
            - "SCHEDULED"
            - "COMPLETED"
            - "CANCELLED"
            - "TO_BE_CONFIRMED"
    AppointmentDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        doctorID:
          type: "integer"
          format: "int32"
        startTime:
          type: "string"
          format: "partial-time"
        date:
          type: "string"
          format: "date"
    AppointmentConfirmationDTO:
      type: "object"
      properties:
        doctor_first_name:
          type: "string"
        doctor_last_name:
          type: "string"
        start_date:
          type: "string"
          format: "date-time"
        patient_first_name:
          type: "string"
        patient_last_name:
          type: "string"
        patient_email:
          type: "string"
        patient_phone:
          type: "string"
        patient_pesel:
          type: "string"
        patient_address:
          type: "string"
        status:
          type: "string"
          enum:
            - "SCHEDULED"
            - "COMPLETED"
            - "CANCELLED"
            - "TO_BE_CONFIRMED"
    DoctorDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        title:
          type: "string"
          enum:
            - "GENERAL"
            - "CARDIOLOGIST"
            - "NEUROLOGIST"
            - "DERMATOLOGIST"
            - "ONCOLOGIST"
            - "PEDIATRICIAN"
            - "PSYCHIATRIST"
            - "OPHTHALMOLOGIST"
            - "GASTROENTEROLOGIST"
            - "ENDOCRINOLOGIST"
