package pl.umcs.medlai.model;

public enum Specialization {
    GENERAL,
    CARDIOLOGIST,
    NEUROLOGIST,
    DERMATOLOGIST,
    ONCOLOGIST,
    PEDIATRICIAN,
    PSYCHIATRIST,
    OPHTHALMOLOGIST,
    GASTROENTEROLOGIST,
    ENDOCRINOLOGIST,
}
